/* eslint-disable */
export default {
  data:[{
    "id" : 422,
    "area" : "海淀区",
    "businessName" : "北京物美商业集团股份有限公司",
    "storageArea" : null,
    "coldStorageArea" : null,
    "numberStaff" : null,
    "numberStaffIstribution" : null,
    "address" : "海淀区西四环北路158号物美大厦",
    "category" : "",
    "contacts" : "",
    "contactNumber" : "",
    "nature" : "民企",
    "street" : "",
    "built_up_area" : null,
    "longitude" : "116.270308352",
    "latitude" : "39.9320061770001",
    "businessType" : 2,
    "createtime" : "2022-04-30 20:24:16",
    "updatetime" : "2022-05-01 12:40:41",
    "distance" : null,
    "count" : null
  }, {
    "id" : 423,
    "area" : "石景山区",
    "businessName" : "北京永辉超市有限公司    ",
    "storageArea" : null,
    "coldStorageArea" : null,
    "numberStaff" : null,
    "numberStaffIstribution" : null,
    "address" : "北京市石景山区石景山路万商大厦",
    "category" : "",
    "contacts" : "",
    "contactNumber" : "",
    "nature" : "民企",
    "street" : "",
    "built_up_area" : null,
    "longitude" : "116.225565",
    "latitude" : "39.91218",
    "businessType" : 2,
    "createtime" : "2022-04-30 20:24:16",
    "updatetime" : "2022-04-30 20:24:16",
    "distance" : null,
    "count" : null
  }, {
    "id" : 424,
    "area" : "朝阳区",
    "businessName" : "北京京客隆商业集团股份有限公司",
    "storageArea" : null,
    "coldStorageArea" : null,
    "numberStaff" : null,
    "numberStaffIstribution" : null,
    "address" : "北京市朝阳区新源街45号",
    "category" : "",
    "contacts" : "",
    "contactNumber" : "",
    "nature" : "区属国企",
    "street" : "",
    "built_up_area" : null,
    "longitude" : "116.461449",
    "latitude" : "39.956552",
    "businessType" : 2,
    "createtime" : "2022-04-30 20:24:16",
    "updatetime" : "2022-04-30 20:24:16",
    "distance" : null,
    "count" : null
  }, {
    "id" : 425,
    "area" : "海淀区",
    "businessName" : "北京超市发连锁股份有限公司",
    "storageArea" : null,
    "coldStorageArea" : null,
    "numberStaff" : null,
    "numberStaffIstribution" : null,
    "address" : " ",
    "category" : "",
    "contacts" : "",
    "contactNumber" : "",
    "nature" : "区属国企",
    "street" : "",
    "built_up_area" : null,
    "longitude" : null,
    "latitude" : null,
    "businessType" : 2,
    "createtime" : "2022-04-30 20:24:16",
    "updatetime" : "2022-04-30 20:24:16",
    "distance" : null,
    "count" : null
  }, {
    "id" : 426,
    "area" : "朝阳区",
    "businessName" : "北京家乐福商业有限公司",
    "storageArea" : null,
    "coldStorageArea" : null,
    "numberStaff" : null,
    "numberStaffIstribution" : null,
    "address" : "北京市朝阳区东八里庄5号昆泰慈云大厦二层",
    "category" : "",
    "contacts" : "",
    "contactNumber" : "",
    "nature" : "合资企业",
    "street" : "",
    "built_up_area" : null,
    "longitude" : "116.502806",
    "latitude" : "39.922031",
    "businessType" : 2,
    "createtime" : "2022-04-30 20:24:16",
    "updatetime" : "2022-04-30 20:24:16",
    "distance" : null,
    "count" : null
  }, {
    "id" : 427,
    "area" : "丰台区",
    "businessName" : "北京首航国力商贸有限公司",
    "storageArea" : null,
    "coldStorageArea" : null,
    "numberStaff" : null,
    "numberStaffIstribution" : null,
    "address" : "北京市丰台区东高地南街7号",
    "category" : "",
    "contacts" : "",
    "contactNumber" : "",
    "nature" : "民企",
    "street" : "",
    "built_up_area" : null,
    "longitude" : "116.424282",
    "latitude" : "39.812349",
    "businessType" : 2,
    "createtime" : "2022-04-30 20:24:16",
    "updatetime" : "2022-04-30 20:24:16",
    "distance" : null,
    "count" : null
  }, {
    "id" : 428,
    "area" : "房山区",
    "businessName" : "北京华冠商业科技发展有限公司",
    "storageArea" : null,
    "coldStorageArea" : null,
    "numberStaff" : null,
    "numberStaffIstribution" : null,
    "address" : "北京市房山区良乡镇小营村村委会东1200米院内201室",
    "category" : "",
    "contacts" : "",
    "contactNumber" : "",
    "nature" : "民企",
    "street" : "",
    "built_up_area" : null,
    "longitude" : "116.172196",
    "latitude" : "39.700009",
    "businessType" : 2,
    "createtime" : "2022-04-30 20:24:16",
    "updatetime" : "2022-04-30 20:24:16",
    "distance" : null,
    "count" : null
  }, {
    "id" : 429,
    "area" : "海淀区",
    "businessName" : "幸福荣耀（北京）超市有限公司",
    "storageArea" : null,
    "coldStorageArea" : null,
    "numberStaff" : null,
    "numberStaffIstribution" : null,
    "address" : "北京市海淀区上地西路宏达商务中心A401",
    "category" : "",
    "contacts" : "",
    "contactNumber" : "",
    "nature" : "民企",
    "street" : "",
    "built_up_area" : null,
    "longitude" : "116.317095",
    "latitude" : "40.035825",
    "businessType" : 2,
    "createtime" : "2022-04-30 20:24:16",
    "updatetime" : "2022-04-30 20:24:16",
    "distance" : null,
    "count" : null
  }, {
    "id" : 430,
    "area" : "西城区",
    "businessName" : "北京华联综合超市股份有限公司",
    "storageArea" : null,
    "coldStorageArea" : null,
    "numberStaff" : null,
    "numberStaffIstribution" : null,
    "address" : "北京市西城区阜外大街1号四川大厦东塔六层",
    "category" : "",
    "contacts" : "",
    "contactNumber" : "",
    "nature" : "民企",
    "street" : "",
    "built_up_area" : null,
    "longitude" : "116.360593",
    "latitude" : "39.930024",
    "businessType" : 2,
    "createtime" : "2022-04-30 20:24:16",
    "updatetime" : "2022-04-30 20:24:16",
    "distance" : null,
    "count" : null
  }, {
    "id" : 431,
    "area" : "朝阳区",
    "businessName" : "沃尔玛（中国）投资有限公司北京分公司",
    "storageArea" : null,
    "coldStorageArea" : null,
    "numberStaff" : null,
    "numberStaffIstribution" : null,
    "address" : "朝阳区东三环中路20号乐成中心A座",
    "category" : "",
    "contacts" : "",
    "contactNumber" : "",
    "nature" : "合资企业",
    "street" : "",
    "built_up_area" : null,
    "longitude" : "116.468993",
    "latitude" : "39.900412",
    "businessType" : 2,
    "createtime" : "2022-04-30 20:24:16",
    "updatetime" : "2022-04-30 20:24:16",
    "distance" : null,
    "count" : null
  }, {
    "id" : 432,
    "area" : "丰台区",
    "businessName" : "北京城乡一一八生活汇超市有限公司",
    "storageArea" : null,
    "coldStorageArea" : null,
    "numberStaff" : null,
    "numberStaffIstribution" : null,
    "address" : "北京市丰台区小屯路149号",
    "category" : "",
    "contacts" : "",
    "contactNumber" : "",
    "nature" : "国企",
    "street" : "",
    "built_up_area" : null,
    "longitude" : "116.262938",
    "latitude" : "39.882065",
    "businessType" : 2,
    "createtime" : "2022-04-30 20:24:16",
    "updatetime" : "2022-04-30 20:24:16",
    "distance" : null,
    "count" : null
  }, {
    "id" : 433,
    "area" : "丰台区",
    "businessName" : "北京天超仓储超市有限责任公司",
    "storageArea" : null,
    "coldStorageArea" : null,
    "numberStaff" : null,
    "numberStaffIstribution" : null,
    "address" : "北京市丰台区右安门外大街2号迦南大厦4层",
    "category" : "",
    "contacts" : "",
    "contactNumber" : "",
    "nature" : "民企",
    "street" : "",
    "built_up_area" : null,
    "longitude" : "116.372734",
    "latitude" : "39.874147",
    "businessType" : 2,
    "createtime" : "2022-04-30 20:24:16",
    "updatetime" : "2022-04-30 20:24:16",
    "distance" : null,
    "count" : null
  }, {
    "id" : 434,
    "area" : "怀柔区",
    "businessName" : "北京大星发商贸有限公司",
    "storageArea" : null,
    "coldStorageArea" : null,
    "numberStaff" : null,
    "numberStaffIstribution" : null,
    "address" : "北京市怀柔区下元市场东侧小泉河东路88号",
    "category" : "",
    "contacts" : "",
    "contactNumber" : "",
    "nature" : "民企",
    "street" : "",
    "built_up_area" : null,
    "longitude" : "116.649541",
    "latitude" : "40.349143",
    "businessType" : 2,
    "createtime" : "2022-04-30 20:24:16",
    "updatetime" : "2022-04-30 20:24:16",
    "distance" : null,
    "count" : null
  }, {
    "id" : 435,
    "area" : "丰台区",
    "businessName" : "北京顺天府商贸有限公司",
    "storageArea" : null,
    "coldStorageArea" : null,
    "numberStaff" : null,
    "numberStaffIstribution" : null,
    "address" : "北京市丰台区东大街31号",
    "category" : "",
    "contacts" : "",
    "contactNumber" : "",
    "nature" : "民企",
    "street" : "",
    "built_up_area" : null,
    "longitude" : "116.299218",
    "latitude" : "39.863824",
    "businessType" : 2,
    "createtime" : "2022-04-30 20:24:16",
    "updatetime" : "2022-04-30 20:24:16",
    "distance" : null,
    "count" : null
  }, {
    "id" : 436,
    "area" : "朝阳区",
    "businessName" : "华润超级市场有限公司",
    "storageArea" : null,
    "coldStorageArea" : null,
    "numberStaff" : null,
    "numberStaffIstribution" : null,
    "address" : "北京市朝阳区道家园18号罗麦大厦",
    "category" : "",
    "contacts" : "",
    "contactNumber" : "",
    "nature" : "国企",
    "street" : "",
    "built_up_area" : null,
    "longitude" : "116.495216",
    "latitude" : "39.930513",
    "businessType" : 2,
    "createtime" : "2022-04-30 20:24:16",
    "updatetime" : "2022-04-30 20:24:16",
    "distance" : null,
    "count" : null
  }, {
    "id" : 437,
    "area" : "朝阳区",
    "businessName" : "北京卜蜂莲花连锁超市有限公司",
    "storageArea" : null,
    "coldStorageArea" : null,
    "numberStaff" : null,
    "numberStaffIstribution" : null,
    "address" : "北京市朝阳区朝阳路太平庄176号",
    "category" : "",
    "contacts" : "",
    "contactNumber" : "",
    "nature" : "合资企业",
    "street" : "",
    "built_up_area" : null,
    "longitude" : "116.527839",
    "latitude" : "39.918306",
    "businessType" : 2,
    "createtime" : "2022-04-30 20:24:16",
    "updatetime" : "2022-04-30 20:24:16",
    "distance" : null,
    "count" : null
  }, {
    "id" : 438,
    "area" : "朝阳区",
    "businessName" : "北京盒马网络科技有限公司",
    "storageArea" : null,
    "coldStorageArea" : null,
    "numberStaff" : null,
    "numberStaffIstribution" : null,
    "address" : "北京市朝阳区望京东园四区9号楼11层1101号",
    "category" : "",
    "contacts" : "",
    "contactNumber" : "",
    "nature" : "民企",
    "street" : "",
    "built_up_area" : null,
    "longitude" : "116.492666",
    "latitude" : "40.006506",
    "businessType" : 2,
    "createtime" : "2022-04-30 20:24:16",
    "updatetime" : "2022-04-30 20:24:16",
    "distance" : null,
    "count" : null
  }, {
    "id" : 439,
    "area" : "经开区",
    "businessName" : "北京期选信息技术有限公司（京东七鲜）",
    "storageArea" : null,
    "coldStorageArea" : null,
    "numberStaff" : null,
    "numberStaffIstribution" : null,
    "address" : "北京市北京经济技术开发区荣华南路2号院大族广场T1座7层",
    "category" : "",
    "contacts" : "",
    "contactNumber" : "",
    "nature" : "民企",
    "street" : "",
    "built_up_area" : null,
    "longitude" : "116.51859",
    "latitude" : "39.799285",
    "businessType" : 2,
    "createtime" : "2022-04-30 20:24:16",
    "updatetime" : "2022-04-30 20:24:16",
    "distance" : null,
    "count" : null
  }, {
    "id" : 448,
    "area" : "东城区\n",
    "businessName" : "北京不姜就电子商务有限公司（叮咚买菜）",
    "storageArea" : null,
    "coldStorageArea" : null,
    "numberStaff" : 13,
    "numberStaffIstribution" : 8,
    "address" : "北京市东城区天坛内东里5号院-10号",
    "category" : "",
    "contacts" : "李前程",
    "contactNumber" : "17634833590",
    "nature" : "",
    "street" : "天坛街道",
    "built_up_area" : null,
    "longitude" : "116.429106",
    "latitude" : "39.882703",
    "businessType" : 5,
    "createtime" : "2022-04-30 20:40:45",
    "updatetime" : "2022-04-30 21:49:04",
    "distance" : null,
    "count" : null
  }, {
    "id" : 449,
    "area" : "东城区",
    "businessName" : "北京不姜就电子商务有限公司（叮咚买菜）",
    "storageArea" : null,
    "coldStorageArea" : null,
    "numberStaff" : 12,
    "numberStaffIstribution" : 8,
    "address" : "北京市东城区东直门外小街甲2号1层106号",
    "category" : "",
    "contacts" : "陈浩",
    "contactNumber" : "15161222556",
    "nature" : "",
    "street" : "东直门街道",
    "built_up_area" : null,
    "longitude" : "116.452855",
    "latitude" : "39.94995",
    "businessType" : 5,
    "createtime" : "2022-04-30 20:40:45",
    "updatetime" : "2022-04-30 20:40:45",
    "distance" : null,
    "count" : null
  }, {
    "id" : 450,
    "area" : "东城区",
    "businessName" : "北京不姜就电子商务有限公司（叮咚买菜）",
    "storageArea" : null,
    "coldStorageArea" : null,
    "numberStaff" : 12,
    "numberStaffIstribution" : 7,
    "address" : "北京市东城区永定门内大街1号",
    "category" : "",
    "contacts" : "王静",
    "contactNumber" : "13716422836",
    "nature" : "",
    "street" : "天坛街道",
    "built_up_area" : null,
    "longitude" : "116.404859",
    "latitude" : "39.886926",
    "businessType" : 5,
    "createtime" : "2022-04-30 20:40:45",
    "updatetime" : "2022-04-30 20:40:45",
    "distance" : null,
    "count" : null
  }, {
    "id" : 451,
    "area" : "西城区\n",
    "businessName" : "北京不姜就电子商务有限公司（叮咚买菜）",
    "storageArea" : null,
    "coldStorageArea" : null,
    "numberStaff" : 14,
    "numberStaffIstribution" : 8,
    "address" : "西城区复兴门外大街路16号39楼",
    "category" : "",
    "contacts" : "靳冰华",
    "contactNumber" : "18303205183",
    "nature" : "",
    "street" : "月坛街道",
    "built_up_area" : null,
    "longitude" : "116.372514",
    "latitude" : "39.918124",
    "businessType" : 5,
    "createtime" : "2022-04-30 20:40:45",
    "updatetime" : "2022-04-30 20:40:45",
    "distance" : null,
    "count" : null
  }, {
    "id" : 452,
    "area" : "西城区\n",
    "businessName" : "北京不姜就电子商务有限公司（叮咚买菜）",
    "storageArea" : null,
    "coldStorageArea" : null,
    "numberStaff" : 12,
    "numberStaffIstribution" : 7,
    "address" : "北京市西城区广外街道小红庙甲14号楼",
    "category" : "",
    "contacts" : "陈晓鹏",
    "contactNumber" : "18729540111",
    "nature" : "",
    "street" : "广外街道",
    "built_up_area" : null,
    "longitude" : "116.343432",
    "latitude" : "39.886413",
    "businessType" : 5,
    "createtime" : "2022-04-30 20:40:45",
    "updatetime" : "2022-04-30 20:40:45",
    "distance" : null,
    "count" : null
  }, {
    "id" : 453,
    "area" : "朝阳区",
    "businessName" : "北京不姜就电子商务有限公司（叮咚买菜）",
    "storageArea" : null,
    "coldStorageArea" : null,
    "numberStaff" : 12,
    "numberStaffIstribution" : 9,
    "address" : "北京市朝阳区民族园2号",
    "category" : "",
    "contacts" : "梁小斌",
    "contactNumber" : "13795426065",
    "nature" : "",
    "street" : "亚运村街道",
    "built_up_area" : null,
    "longitude" : "116.397753",
    "latitude" : "39.988523",
    "businessType" : 5,
    "createtime" : "2022-04-30 20:40:45",
    "updatetime" : "2022-04-30 20:40:45",
    "distance" : null,
    "count" : null
  }, {
    "id" : 454,
    "area" : "朝阳区",
    "businessName" : "北京不姜就电子商务有限公司（叮咚买菜）",
    "storageArea" : null,
    "coldStorageArea" : null,
    "numberStaff" : 12,
    "numberStaffIstribution" : 10,
    "address" : "北京市朝阳区三间房乡东柳村1号",
    "category" : "",
    "contacts" : "安然",
    "contactNumber" : "13051531758",
    "nature" : "",
    "street" : "三间房街道",
    "built_up_area" : null,
    "longitude" : "116.583966",
    "latitude" : "39.907573",
    "businessType" : 5,
    "createtime" : "2022-04-30 20:40:45",
    "updatetime" : "2022-04-30 20:40:45",
    "distance" : null,
    "count" : null
  }, {
    "id" : 455,
    "area" : "朝阳区",
    "businessName" : "北京不姜就电子商务有限公司（叮咚买菜）",
    "storageArea" : null,
    "coldStorageArea" : null,
    "numberStaff" : 11,
    "numberStaffIstribution" : 7,
    "address" : "朝阳区黄杉木店路116号远策中心",
    "category" : "",
    "contacts" : "刘佳兴",
    "contactNumber" : "15100543313",
    "nature" : "",
    "street" : "平房街道",
    "built_up_area" : null,
    "longitude" : "116.528992",
    "latitude" : "39.93697",
    "businessType" : 5,
    "createtime" : "2022-04-30 20:40:45",
    "updatetime" : "2022-04-30 20:40:45",
    "distance" : null,
    "count" : null
  }, {
    "id" : 456,
    "area" : "朝阳区",
    "businessName" : "北京不姜就电子商务有限公司（叮咚买菜）",
    "storageArea" : null,
    "coldStorageArea" : null,
    "numberStaff" : 12,
    "numberStaffIstribution" : 10,
    "address" : "北京市朝阳区青年路朝阳路路口甘露园4号物美超市入口地下负1层",
    "category" : "",
    "contacts" : "孙晓红",
    "contactNumber" : "17778091314",
    "nature" : "",
    "street" : "八里庄街道",
    "built_up_area" : null,
    "longitude" : "116.518796",
    "latitude" : "39.923086",
    "businessType" : 5,
    "createtime" : "2022-04-30 20:40:45",
    "updatetime" : "2022-04-30 20:40:45",
    "distance" : null,
    "count" : null
  }, {
    "id" : 457,
    "area" : "朝阳区",
    "businessName" : "北京不姜就电子商务有限公司（叮咚买菜）",
    "storageArea" : null,
    "coldStorageArea" : null,
    "numberStaff" : 12,
    "numberStaffIstribution" : 9,
    "address" : "北京市朝阳区小营路8号7天酒店",
    "category" : "",
    "contacts" : "张宏鹏",
    "contactNumber" : "18513733458",
    "nature" : "",
    "street" : "大屯街道",
    "built_up_area" : null,
    "longitude" : "116.432948",
    "latitude" : "40.001484",
    "businessType" : 5,
    "createtime" : "2022-04-30 20:40:45",
    "updatetime" : "2022-04-30 20:40:45",
    "distance" : null,
    "count" : null
  }, {
    "id" : 458,
    "area" : "朝阳区",
    "businessName" : "北京不姜就电子商务有限公司（叮咚买菜）",
    "storageArea" : null,
    "coldStorageArea" : null,
    "numberStaff" : 12,
    "numberStaffIstribution" : 10,
    "address" : "北京市朝阳区西坝河中里6号楼",
    "category" : "",
    "contacts" : "高峰",
    "contactNumber" : "19910613150",
    "nature" : "",
    "street" : "香河园街道",
    "built_up_area" : null,
    "longitude" : "116.44932",
    "latitude" : "39.970317",
    "businessType" : 5,
    "createtime" : "2022-04-30 20:40:45",
    "updatetime" : "2022-04-30 20:40:45",
    "distance" : null,
    "count" : null
  }, {
    "id" : 459,
    "area" : "朝阳区",
    "businessName" : "北京不姜就电子商务有限公司（叮咚买菜）",
    "storageArea" : null,
    "coldStorageArea" : null,
    "numberStaff" : 12,
    "numberStaffIstribution" : 7,
    "address" : "北京市朝阳区化工路58号10-05",
    "category" : "",
    "contacts" : "马栋栋",
    "contactNumber" : "18835718890",
    "nature" : "",
    "street" : "王四营乡",
    "built_up_area" : null,
    "longitude" : "116.521082",
    "latitude" : "39.870494",
    "businessType" : 5,
    "createtime" : "2022-04-30 20:40:45",
    "updatetime" : "2022-04-30 20:40:45",
    "distance" : null,
    "count" : null
  }, {
    "id" : 460,
    "area" : "朝阳区",
    "businessName" : "北京不姜就电子商务有限公司（叮咚买菜）",
    "storageArea" : null,
    "coldStorageArea" : null,
    "numberStaff" : 11,
    "numberStaffIstribution" : 9,
    "address" : "北京市朝阳区左安路1号十里河文化园c座",
    "category" : "",
    "contacts" : "王洋",
    "contactNumber" : "15144611118",
    "nature" : "",
    "street" : "十八里店地区",
    "built_up_area" : null,
    "longitude" : "116.464635",
    "latitude" : "39.873068",
    "businessType" : 5,
    "createtime" : "2022-04-30 20:40:45",
    "updatetime" : "2022-04-30 20:40:45",
    "distance" : null,
    "count" : null
  }, {
    "id" : 461,
    "area" : "朝阳区",
    "businessName" : "北京不姜就电子商务有限公司（叮咚买菜）",
    "storageArea" : null,
    "coldStorageArea" : null,
    "numberStaff" : 12,
    "numberStaffIstribution" : 10,
    "address" : "北京市朝阳区望京总工会中广怡景湾503号楼底商一层叮咚买菜",
    "category" : "",
    "contacts" : "马云超",
    "contactNumber" : "17310787555",
    "nature" : "",
    "street" : "望京西街道",
    "built_up_area" : null,
    "longitude" : "116.461143",
    "latitude" : "39.994562",
    "businessType" : 5,
    "createtime" : "2022-04-30 20:40:45",
    "updatetime" : "2022-04-30 20:40:45",
    "distance" : null,
    "count" : null
  }, {
    "id" : 462,
    "area" : "朝阳区",
    "businessName" : "北京不姜就电子商务有限公司（叮咚买菜）",
    "storageArea" : null,
    "coldStorageArea" : null,
    "numberStaff" : 11,
    "numberStaffIstribution" : 7,
    "address" : "北京市朝阳区松榆南路38号院9号楼一层",
    "category" : "",
    "contacts" : "徐恩新",
    "contactNumber" : "15660419958",
    "nature" : "",
    "street" : "南磨坊街道",
    "built_up_area" : null,
    "longitude" : "116.47628",
    "latitude" : "39.877092",
    "businessType" : 5,
    "createtime" : "2022-04-30 20:40:45",
    "updatetime" : "2022-04-30 20:40:45",
    "distance" : null,
    "count" : null
  }, {
    "id" : 463,
    "area" : "朝阳区",
    "businessName" : "北京不姜就电子商务有限公司（叮咚买菜）",
    "storageArea" : null,
    "coldStorageArea" : null,
    "numberStaff" : 12,
    "numberStaffIstribution" : 10,
    "address" : "北京市朝阳区酒仙桥路13号瀚海国际大厦1层右边停车场",
    "category" : "",
    "contacts" : "骈利钦",
    "contactNumber" : "13699158155",
    "nature" : "",
    "street" : "酒仙桥街道",
    "built_up_area" : null,
    "longitude" : "116.495663",
    "latitude" : "39.984346",
    "businessType" : 5,
    "createtime" : "2022-04-30 20:40:45",
    "updatetime" : "2022-04-30 20:40:45",
    "distance" : null,
    "count" : null
  }, {
    "id" : 464,
    "area" : "朝阳区",
    "businessName" : "北京不姜就电子商务有限公司（叮咚买菜）",
    "storageArea" : null,
    "coldStorageArea" : null,
    "numberStaff" : 14,
    "numberStaffIstribution" : 9,
    "address" : "北京市朝阳区小红门乡龙爪树南里68号院5-114-115",
    "category" : "",
    "contacts" : "辛晨",
    "contactNumber" : "13911182696",
    "nature" : "",
    "street" : "小红门地区",
    "built_up_area" : null,
    "longitude" : "116.462608",
    "latitude" : "39.847443",
    "businessType" : 5,
    "createtime" : "2022-04-30 20:40:45",
    "updatetime" : "2022-04-30 20:40:45",
    "distance" : null,
    "count" : null
  }, {
    "id" : 465,
    "area" : "朝阳区",
    "businessName" : "北京不姜就电子商务有限公司（叮咚买菜）",
    "storageArea" : null,
    "coldStorageArea" : null,
    "numberStaff" : 13,
    "numberStaffIstribution" : 8,
    "address" : "朝阳区东坝中路朝新家园东里一区5号楼",
    "category" : "",
    "contacts" : "黄涛",
    "contactNumber" : "18810392962",
    "nature" : "",
    "street" : "东坝乡",
    "built_up_area" : null,
    "longitude" : "116.561123",
    "latitude" : "39.954922",
    "businessType" : 5,
    "createtime" : "2022-04-30 20:40:45",
    "updatetime" : "2022-04-30 20:40:45",
    "distance" : null,
    "count" : null
  }, {
    "id" : 466,
    "area" : "朝阳区",
    "businessName" : "北京不姜就电子商务有限公司（叮咚买菜）",
    "storageArea" : null,
    "coldStorageArea" : null,
    "numberStaff" : 12,
    "numberStaffIstribution" : 10,
    "address" : "北京市朝阳区朝阳北路58号A2号楼一层A104.A114",
    "category" : "",
    "contacts" : "高建东",
    "contactNumber" : "18790892000",
    "nature" : "",
    "street" : "三间房街道",
    "built_up_area" : null,
    "longitude" : "116.556468",
    "latitude" : "39.929338",
    "businessType" : 5,
    "createtime" : "2022-04-30 20:40:45",
    "updatetime" : "2022-04-30 20:40:45",
    "distance" : null,
    "count" : null
  }, {
    "id" : 467,
    "area" : "朝阳区",
    "businessName" : "北京不姜就电子商务有限公司（叮咚买菜）",
    "storageArea" : null,
    "coldStorageArea" : null,
    "numberStaff" : 12,
    "numberStaffIstribution" : 8,
    "address" : "北京市朝阳区金时代购物广场一层",
    "category" : "",
    "contacts" : "王赛赛",
    "contactNumber" : "13569333464",
    "nature" : "",
    "street" : "管庄街道",
    "built_up_area" : null,
    "longitude" : "116.597815",
    "latitude" : "39.919646",
    "businessType" : 5,
    "createtime" : "2022-04-30 20:40:45",
    "updatetime" : "2022-04-30 20:40:45",
    "distance" : null,
    "count" : null
  }, {
    "id" : 468,
    "area" : "朝阳区",
    "businessName" : "北京不姜就电子商务有限公司（叮咚买菜）",
    "storageArea" : null,
    "coldStorageArea" : null,
    "numberStaff" : 12,
    "numberStaffIstribution" : 8,
    "address" : "北京市朝阳区崔各庄乡京旺家园小区底商七区13号楼C1-2",
    "category" : "",
    "contacts" : "袁玉松",
    "contactNumber" : "17611142680",
    "nature" : "",
    "street" : "崔各庄街道",
    "built_up_area" : null,
    "longitude" : "116.535209",
    "latitude" : "40.017537",
    "businessType" : 5,
    "createtime" : "2022-04-30 20:40:45",
    "updatetime" : "2022-04-30 20:40:45",
    "distance" : null,
    "count" : null
  }, {
    "id" : 469,
    "area" : "朝阳区",
    "businessName" : "北京不姜就电子商务有限公司（叮咚买菜）",
    "storageArea" : null,
    "coldStorageArea" : null,
    "numberStaff" : 12,
    "numberStaffIstribution" : 8,
    "address" : "北京市朝阳区813文化产业园6号楼610",
    "category" : "",
    "contacts" : "吴贺",
    "contactNumber" : "18251622876",
    "nature" : "",
    "street" : "王四营街道",
    "built_up_area" : null,
    "longitude" : "116.483037",
    "latitude" : "39.906557",
    "businessType" : 5,
    "createtime" : "2022-04-30 20:40:45",
    "updatetime" : "2022-04-30 20:40:45",
    "distance" : null,
    "count" : null
  }, {
    "id" : 470,
    "area" : "朝阳区",
    "businessName" : "北京不姜就电子商务有限公司（叮咚买菜）",
    "storageArea" : null,
    "coldStorageArea" : null,
    "numberStaff" : 11,
    "numberStaffIstribution" : 7,
    "address" : "北京市朝阳区吕家营村京吕建业",
    "category" : "",
    "contacts" : "夏吉祥",
    "contactNumber" : "13717912235",
    "nature" : "",
    "street" : "十八里店地区",
    "built_up_area" : null,
    "longitude" : "116.47292",
    "latitude" : "39.841516",
    "businessType" : 5,
    "createtime" : "2022-04-30 20:40:45",
    "updatetime" : "2022-04-30 20:40:45",
    "distance" : null,
    "count" : null
  }, {
    "id" : 471,
    "area" : "朝阳区",
    "businessName" : "北京不姜就电子商务有限公司（叮咚买菜）",
    "storageArea" : null,
    "coldStorageArea" : null,
    "numberStaff" : 12,
    "numberStaffIstribution" : 9,
    "address" : "北京市朝阳区广渠路66号院8号",
    "category" : "",
    "contacts" : "张飞飞",
    "contactNumber" : "15210532759",
    "nature" : "",
    "street" : "劲松街道",
    "built_up_area" : null,
    "longitude" : "116.472352",
    "latitude" : "39.894633",
    "businessType" : 5,
    "createtime" : "2022-04-30 20:40:45",
    "updatetime" : "2022-04-30 20:40:45",
    "distance" : null,
    "count" : null
  }, {
    "id" : 472,
    "area" : "朝阳区",
    "businessName" : "北京不姜就电子商务有限公司（叮咚买菜）",
    "storageArea" : null,
    "coldStorageArea" : null,
    "numberStaff" : 12,
    "numberStaffIstribution" : 10,
    "address" : "北京市朝阳区朝外大街26号F1-23号",
    "category" : "",
    "contacts" : "李飞",
    "contactNumber" : "13683367170",
    "nature" : "",
    "street" : "朝外街道",
    "built_up_area" : null,
    "longitude" : "116.448157",
    "latitude" : "39.927938",
    "businessType" : 5,
    "createtime" : "2022-04-30 20:40:45",
    "updatetime" : "2022-04-30 20:40:45",
    "distance" : null,
    "count" : null
  }, {
    "id" : 473,
    "area" : "朝阳区",
    "businessName" : "北京不姜就电子商务有限公司（叮咚买菜）",
    "storageArea" : null,
    "coldStorageArea" : null,
    "numberStaff" : 12,
    "numberStaffIstribution" : 10,
    "address" : "北京市朝阳区朝来绿色家园来春园37号楼101室及102部分",
    "category" : "",
    "contacts" : "杨东光",
    "contactNumber" : "13911960917",
    "nature" : "",
    "street" : "来广营地区",
    "built_up_area" : null,
    "longitude" : "116.445393",
    "latitude" : "40.042008",
    "businessType" : 5,
    "createtime" : "2022-04-30 20:40:45",
    "updatetime" : "2022-04-30 20:40:45",
    "distance" : null,
    "count" : null
  }, {
    "id" : 474,
    "area" : "朝阳区",
    "businessName" : "北京不姜就电子商务有限公司（叮咚买菜）",
    "storageArea" : null,
    "coldStorageArea" : null,
    "numberStaff" : 11,
    "numberStaffIstribution" : 9,
    "address" : "北京市朝阳区北苑东路水岸庄园351号楼",
    "category" : "",
    "contacts" : "孙笑凯",
    "contactNumber" : "18600721641",
    "nature" : "",
    "street" : "水岸中街道",
    "built_up_area" : null,
    "longitude" : "116.447756",
    "latitude" : "40.060538",
    "businessType" : 5,
    "createtime" : "2022-04-30 20:40:45",
    "updatetime" : "2022-04-30 20:40:45",
    "distance" : null,
    "count" : null
  }, {
    "id" : 475,
    "area" : "朝阳区",
    "businessName" : "北京不姜就电子商务有限公司（叮咚买菜）",
    "storageArea" : null,
    "coldStorageArea" : null,
    "numberStaff" : 12,
    "numberStaffIstribution" : 9,
    "address" : "北京市朝阳区区北辰东路路 慧忠里304号楼1层304-2",
    "category" : "",
    "contacts" : "杨志超",
    "contactNumber" : "17613910615",
    "nature" : "",
    "street" : "大屯街道",
    "built_up_area" : null,
    "longitude" : "116.407636",
    "latitude" : "40.004004",
    "businessType" : 5,
    "createtime" : "2022-04-30 20:40:45",
    "updatetime" : "2022-04-30 20:40:45",
    "distance" : null,
    "count" : null
  }, {
    "id" : 476,
    "area" : "朝阳区",
    "businessName" : "北京不姜就电子商务有限公司（叮咚买菜）",
    "storageArea" : null,
    "coldStorageArea" : null,
    "numberStaff" : 12,
    "numberStaffIstribution" : 9,
    "address" : "北京市朝阳区豆各庄乡锦龙文化园",
    "category" : "",
    "contacts" : "李丹丹",
    "contactNumber" : "15998615763",
    "nature" : "",
    "street" : "豆各庄乡",
    "built_up_area" : null,
    "longitude" : "116.578939",
    "latitude" : "39.878625",
    "businessType" : 5,
    "createtime" : "2022-04-30 20:40:45",
    "updatetime" : "2022-04-30 20:40:45",
    "distance" : null,
    "count" : null
  }, {
    "id" : 477,
    "area" : "朝阳区",
    "businessName" : "北京不姜就电子商务有限公司（叮咚买菜）",
    "storageArea" : null,
    "coldStorageArea" : null,
    "numberStaff" : 12,
    "numberStaffIstribution" : 10,
    "address" : "北京市朝阳区双桥东路甲8号一层西侧",
    "category" : "",
    "contacts" : "韩彦五",
    "contactNumber" : "16603741649",
    "nature" : "",
    "street" : "管庄街道",
    "built_up_area" : null,
    "longitude" : "116.609135",
    "latitude" : "39.907411",
    "businessType" : 5,
    "createtime" : "2022-04-30 20:40:45",
    "updatetime" : "2022-04-30 20:40:45",
    "distance" : null,
    "count" : null
  }, {
    "id" : 478,
    "area" : "朝阳区",
    "businessName" : "北京不姜就电子商务有限公司（叮咚买菜）",
    "storageArea" : null,
    "coldStorageArea" : null,
    "numberStaff" : 13,
    "numberStaffIstribution" : 11,
    "address" : "北京市朝阳区来广营东路98号",
    "category" : "",
    "contacts" : "朱静",
    "contactNumber" : "18930677725",
    "nature" : "",
    "street" : "马南里社区居委会",
    "built_up_area" : null,
    "longitude" : "116.509016",
    "latitude" : "40.029206",
    "businessType" : 5,
    "createtime" : "2022-04-30 20:40:45",
    "updatetime" : "2022-04-30 20:40:45",
    "distance" : null,
    "count" : null
  }, {
    "id" : 479,
    "area" : "朝阳区",
    "businessName" : "北京不姜就电子商务有限公司（叮咚买菜）",
    "storageArea" : null,
    "coldStorageArea" : null,
    "numberStaff" : 12,
    "numberStaffIstribution" : 10,
    "address" : "北京市朝阳区八里庄北里87号南楼京师音乐广场一层107室",
    "category" : "",
    "contacts" : "杨晓进",
    "contactNumber" : "15600750016",
    "nature" : "",
    "street" : "六里屯街道",
    "built_up_area" : null,
    "longitude" : "116.50084",
    "latitude" : "39.927343",
    "businessType" : 5,
    "createtime" : "2022-04-30 20:40:45",
    "updatetime" : "2022-04-30 20:40:45",
    "distance" : null,
    "count" : null
  }, {
    "id" : 480,
    "area" : "朝阳区",
    "businessName" : "北京不姜就电子商务有限公司（叮咚买菜）",
    "storageArea" : null,
    "coldStorageArea" : null,
    "numberStaff" : 12,
    "numberStaffIstribution" : 10,
    "address" : "北京市朝阳区黄寺大街5号之房屋",
    "category" : "",
    "contacts" : "王向垒",
    "contactNumber" : "13311401083",
    "nature" : "",
    "street" : "安贞街道",
    "built_up_area" : null,
    "longitude" : "116.400568",
    "latitude" : "39.9707",
    "businessType" : 5,
    "createtime" : "2022-04-30 20:40:45",
    "updatetime" : "2022-04-30 20:40:45",
    "distance" : null,
    "count" : null
  }, {
    "id" : 481,
    "area" : "朝阳区",
    "businessName" : "北京不姜就电子商务有限公司（叮咚买菜）",
    "storageArea" : null,
    "coldStorageArea" : null,
    "numberStaff" : 12,
    "numberStaffIstribution" : 9,
    "address" : "北京市朝阳区广顺北大街5号-3之房屋",
    "category" : "",
    "contacts" : "姚宇飞",
    "contactNumber" : "17600564817",
    "nature" : "",
    "street" : "来广营街道",
    "built_up_area" : null,
    "longitude" : "116.47338",
    "latitude" : "40.024088",
    "businessType" : 5,
    "createtime" : "2022-04-30 20:40:45",
    "updatetime" : "2022-04-30 20:40:45",
    "distance" : null,
    "count" : null
  }, {
    "id" : 482,
    "area" : "朝阳区",
    "businessName" : "北京不姜就电子商务有限公司（叮咚买菜）",
    "storageArea" : null,
    "coldStorageArea" : null,
    "numberStaff" : 12,
    "numberStaffIstribution" : 9,
    "address" : "北京市朝阳区工体东路20号",
    "category" : "",
    "contacts" : "姚秀龙",
    "contactNumber" : "17600485617",
    "nature" : "",
    "street" : "呼家楼街道",
    "built_up_area" : null,
    "longitude" : "116.45752",
    "latitude" : "39.929994",
    "businessType" : 5,
    "createtime" : "2022-04-30 20:40:45",
    "updatetime" : "2022-04-30 20:40:45",
    "distance" : null,
    "count" : null
  }, {
    "id" : 483,
    "area" : "朝阳区",
    "businessName" : "北京不姜就电子商务有限公司（叮咚买菜）",
    "storageArea" : null,
    "coldStorageArea" : null,
    "numberStaff" : 12,
    "numberStaffIstribution" : 10,
    "address" : "北京市朝阳区西坝河东里101号楼一层106",
    "category" : "",
    "contacts" : "陈志鑫",
    "contactNumber" : "13502070511",
    "nature" : "",
    "street" : "香河园街道",
    "built_up_area" : null,
    "longitude" : "116.450971",
    "latitude" : "39.973647",
    "businessType" : 5,
    "createtime" : "2022-04-30 20:40:45",
    "updatetime" : "2022-04-30 20:40:45",
    "distance" : null,
    "count" : null
  }, {
    "id" : 484,
    "area" : "朝阳区",
    "businessName" : "北京不姜就电子商务有限公司（叮咚买菜）",
    "storageArea" : null,
    "coldStorageArea" : null,
    "numberStaff" : 11,
    "numberStaffIstribution" : 7,
    "address" : "北京市朝阳区高碑店乡高碑店村医药物流区1525号3号楼A109室",
    "category" : "",
    "contacts" : "郭锐",
    "contactNumber" : "17798425707",
    "nature" : "",
    "street" : "高碑店镇",
    "built_up_area" : null,
    "longitude" : "116.543643",
    "latitude" : "39.912759",
    "businessType" : 5,
    "createtime" : "2022-04-30 20:40:45",
    "updatetime" : "2022-04-30 20:40:45",
    "distance" : null,
    "count" : null
  }, {
    "id" : 485,
    "area" : "朝阳区",
    "businessName" : "北京不姜就电子商务有限公司（叮咚买菜）",
    "storageArea" : null,
    "coldStorageArea" : null,
    "numberStaff" : 12,
    "numberStaffIstribution" : 10,
    "address" : "北京市朝阳区利泽东园308号1单元1层1011",
    "category" : "",
    "contacts" : "习梦想",
    "contactNumber" : "17518959972",
    "nature" : "",
    "street" : "利泽中街",
    "built_up_area" : null,
    "longitude" : "116.485603",
    "latitude" : "40.018955",
    "businessType" : 5,
    "createtime" : "2022-04-30 20:40:45",
    "updatetime" : "2022-04-30 20:40:45",
    "distance" : null,
    "count" : null
  }, {
    "id" : 486,
    "area" : "朝阳区",
    "businessName" : "北京不姜就电子商务有限公司（叮咚买菜）",
    "storageArea" : null,
    "coldStorageArea" : null,
    "numberStaff" : 12,
    "numberStaffIstribution" : 8,
    "address" : "北京市朝阳区朝阳体育中心西路808产业园2号楼B座一层东侧101",
    "category" : "",
    "contacts" : "张磊",
    "contactNumber" : "17719027267",
    "nature" : "",
    "street" : "高杨树中街",
    "built_up_area" : null,
    "longitude" : "116.148692",
    "latitude" : "39.741213",
    "businessType" : 5,
    "createtime" : "2022-04-30 20:40:45",
    "updatetime" : "2022-04-30 20:40:45",
    "distance" : null,
    "count" : null
  }, {
    "id" : 487,
    "area" : "朝阳区",
    "businessName" : "北京不姜就电子商务有限公司（叮咚买菜）",
    "storageArea" : null,
    "coldStorageArea" : null,
    "numberStaff" : 12,
    "numberStaffIstribution" : 10,
    "address" : "北京市朝阳区西大望路27号144幢",
    "category" : "",
    "contacts" : "刘天宇",
    "contactNumber" : "15054125554",
    "nature" : "",
    "street" : "朝阳区劲松街道",
    "built_up_area" : null,
    "longitude" : "116.485205",
    "latitude" : "39.890529",
    "businessType" : 5,
    "createtime" : "2022-04-30 20:40:45",
    "updatetime" : "2022-04-30 20:40:45",
    "distance" : null,
    "count" : null
  }, {
    "id" : 488,
    "area" : "朝阳区",
    "businessName" : "北京不姜就电子商务有限公司（叮咚买菜）",
    "storageArea" : null,
    "coldStorageArea" : null,
    "numberStaff" : 14,
    "numberStaffIstribution" : 8,
    "address" : "北京市朝阳区驼房营南路8号路南侧一层103",
    "category" : "",
    "contacts" : "孙玥玥",
    "contactNumber" : "15102259952",
    "nature" : "",
    "street" : "酒仙桥街道",
    "built_up_area" : null,
    "longitude" : "116.50924",
    "latitude" : "39.969957",
    "businessType" : 5,
    "createtime" : "2022-04-30 20:40:45",
    "updatetime" : "2022-04-30 20:40:45",
    "distance" : null,
    "count" : null
  }, {
    "id" : 489,
    "area" : "朝阳区",
    "businessName" : "北京不姜就电子商务有限公司（叮咚买菜）",
    "storageArea" : null,
    "coldStorageArea" : null,
    "numberStaff" : 12,
    "numberStaffIstribution" : 10,
    "address" : "北京市朝阳区朝阳路七号院",
    "category" : "",
    "contacts" : "张霞",
    "contactNumber" : "18567322946",
    "nature" : "",
    "street" : "酒仙桥街道",
    "built_up_area" : null,
    "longitude" : "116.611652",
    "latitude" : "39.920411",
    "businessType" : 5,
    "createtime" : "2022-04-30 20:40:45",
    "updatetime" : "2022-04-30 20:40:45",
    "distance" : null,
    "count" : null
  }, {
    "id" : 490,
    "area" : "朝阳区",
    "businessName" : "北京不姜就电子商务有限公司（叮咚买菜）",
    "storageArea" : null,
    "coldStorageArea" : null,
    "numberStaff" : 12,
    "numberStaffIstribution" : 8,
    "address" : "北京市朝阳区十里铺东里126号楼1层101",
    "category" : "",
    "contacts" : "邢赛赛",
    "contactNumber" : "15557157801",
    "nature" : "",
    "street" : "呼家楼街道",
    "built_up_area" : null,
    "longitude" : "116.514544",
    "latitude" : "39.924582",
    "businessType" : 5,
    "createtime" : "2022-04-30 20:40:45",
    "updatetime" : "2022-04-30 20:40:45",
    "distance" : null,
    "count" : null
  }, {
    "id" : 491,
    "area" : "海淀区\n",
    "businessName" : "北京不姜就电子商务有限公司（叮咚买菜）",
    "storageArea" : null,
    "coldStorageArea" : null,
    "numberStaff" : 12,
    "numberStaffIstribution" : 9,
    "address" : "北京市海淀区西三条9号",
    "category" : "",
    "contacts" : "方忠宝",
    "contactNumber" : "13079765204",
    "nature" : "",
    "street" : "清河街道",
    "built_up_area" : null,
    "longitude" : "116.369441",
    "latitude" : "39.871186",
    "businessType" : 5,
    "createtime" : "2022-04-30 20:40:45",
    "updatetime" : "2022-04-30 20:40:45",
    "distance" : null,
    "count" : null
  }, {
    "id" : 492,
    "area" : "海淀区\n",
    "businessName" : "北京不姜就电子商务有限公司（叮咚买菜）",
    "storageArea" : null,
    "coldStorageArea" : null,
    "numberStaff" : 12,
    "numberStaffIstribution" : 11,
    "address" : "北京市海淀区四道口路2号",
    "category" : "",
    "contacts" : "丛大有",
    "contactNumber" : "17701382969",
    "nature" : "",
    "street" : "北下关街道",
    "built_up_area" : null,
    "longitude" : "116.352689",
    "latitude" : "39.964998",
    "businessType" : 5,
    "createtime" : "2022-04-30 20:40:45",
    "updatetime" : "2022-04-30 20:40:45",
    "distance" : null,
    "count" : null
  }, {
    "id" : 493,
    "area" : "海淀区\n",
    "businessName" : "北京不姜就电子商务有限公司（叮咚买菜）",
    "storageArea" : null,
    "coldStorageArea" : null,
    "numberStaff" : 12,
    "numberStaffIstribution" : 10,
    "address" : "北京市海淀区中关村东路大钟寺西路汉荣家园西门",
    "category" : "",
    "contacts" : "石岩",
    "contactNumber" : "18245336765",
    "nature" : "",
    "street" : "中关村街道",
    "built_up_area" : null,
    "longitude" : "116.343379",
    "latitude" : "39.978666",
    "businessType" : 5,
    "createtime" : "2022-04-30 20:40:45",
    "updatetime" : "2022-04-30 20:40:45",
    "distance" : null,
    "count" : null
  }, {
    "id" : 494,
    "area" : "海淀区\n",
    "businessName" : "北京不姜就电子商务有限公司（叮咚买菜）",
    "storageArea" : null,
    "coldStorageArea" : null,
    "numberStaff" : 12,
    "numberStaffIstribution" : 10,
    "address" : "北京市海淀区西三环北路50号",
    "category" : "",
    "contacts" : "韩正科",
    "contactNumber" : "18437396252",
    "nature" : "",
    "street" : "紫竹院街道",
    "built_up_area" : null,
    "longitude" : "116.319455",
    "latitude" : "39.945594",
    "businessType" : 5,
    "createtime" : "2022-04-30 20:40:45",
    "updatetime" : "2022-04-30 20:40:45",
    "distance" : null,
    "count" : null
  }]
}